
[env]
  TERM = "xterm-256color"

[window]
  padding = { x = 5, y = 5 }

[font]
  normal = { family = "FiraCode Nerd Font", style = "Regular" }
  bold = { family = "FiraCode Nerd Font", style = "Bold" }
  italic = { family = "FiraCode Nerd Font", style = "Italic" }
  size = 13

